Helm config for auto-APM in all deployments
ndustrialio/charts pull request #16
Opened 2021-07-28 18:18 UTC by skmannion

2021-07-28 22:29 UTC, kalinon requested changes

2021-07-28 22:29 UTC, kalinon commented on ndustrial/deployment/templates/deployment.yaml
> +            - name: DATADOG_TRACE_AGENT_HOSTNAME
need to add the other envs as well.

Also should add a values entry for enabling datadog or not. aka:

```
datadog:
  apm:
    enabled: false
    # add more default/customizable apm fields here if needed
```

then wrap the datadog envs in a if block:
```
{{- if .Values.datadog.apm.enabled }}
# put envs here
{{- end }}
```

2021-07-29 12:45 UTC, kalinon commented on ndustrial/deployment/templates/deployment.yaml
> +            {{- if .Values.datadog.apm.trace_agent_hostname }}
is this specific to apm?

2021-07-29 12:49 UTC, kalinon requested changes

2021-07-29 12:49 UTC, kalinon commented on ndustrial/deployment/values.yaml
> +    trace_agent_host: null
Do we want these all as `null`? also, are these all apm specific? or can they be used without `apm`? guess im asking if they should be nested under apm.

2021-07-29 12:49 UTC, kalinon commented on ndustrial/deployment/templates/deployment.yaml
> +              value: {{ .Values.datadog.node_env }}
think your pathing is wrong. should be like `.Values.datadog.apm.node_env`

2021-07-29 12:49 UTC, kalinon commented on ndustrial/deployment/values.yaml
> +    trace_agent_host: null
Also need to add documentation annotations. see: https://github.com/bitnami-labs/readme-generator-for-helm and other vars for examples

2021-07-29 12:56 UTC, skmannion commented on ndustrial/deployment/templates/deployment.yaml
> +            {{- if .Values.datadog.apm.trace_agent_hostname }}
Yes believe all of these configs are. They're all used by the ddtrace library and I think traces are an APM thing

2021-07-29 12:58 UTC, kalinon approved these changes

2021-07-29 12:58 UTC, skmannion commented on ndustrial/deployment/templates/deployment.yaml
> +              value: {{ .Values.datadog.node_env }}
Yup, knew I needed that change. Caught it in most recent commit.

2021-07-29 12:58 UTC, kalinon requested changes
default values need to be set or each env wrapped in an `if` statement

2021-07-30 12:20 UTC, closed without merging