Update Stateful Chart
ndustrialio/charts pull request #23
Opened 2021-08-18 21:34 UTC by jeffdyoung

- Give StatefulSet a default volume
- Make StatefulSet Service optional
- update readme.md to match expected `project` and `type`

2021-08-19 12:49 UTC, kalinon requested changes

2021-08-19 12:49 UTC, kalinon commented on ndustrial/statefulset/templates/statefuleset.yaml
> +            storage: {{ .Values.storage.size }}
Should we wrap this in a `if` statement? like check for `persistance.enabled`? Also i would use `persistance` instead of `storage` since it seems its the standard in most helm charts.

2021-08-19 12:49 UTC, kalinon commented on ndustrial/statefulset/templates/statefuleset.yaml
> +              name: {{ include "common.names.fullname" . }}
Same here. should wrap in `if` statement.

2021-08-19 12:49 UTC, kalinon commented on ndustrial/statefulset/values.yaml
> +storage:
change to `persistence`?

2021-08-19 18:01 UTC, jeffdyoung commented
@kalinon Changed to `persistentVolume`  you good with that?

2021-08-24 13:20 UTC, kalinon approved these changes

2021-08-24 13:20 UTC, merged